# Wallpaper setup!
# To reload when you update config: Run `killall hyprpaper` and then `hyperpaper & disown`

# run `hyprctl monitors all` to see all your monitors!!! In order to create your setup.

wallpaper {
    monitor = eDP-1
    path = /home/lain/Pictures/aero/HIRAETH.png
    fit_mode = cover
}
